drop procedure src_sps_contenido_total_taller_bo
go

drop procedure src_spu_estado_contenido_bo
go

drop procedure src_sps_contenido_taller_bo
go

drop procedure src_spi_contenido_taller_bo
go

drop procedure src_sps_codigo_contenido_bo
go

drop procedure src_sps_bandeja_contenido_informativo_bo
go

drop procedure SRC_SPS_TIPO_CONTENIDO_INFORMATIVO_bo
go

drop procedure SRC_SPS_ESTADOS_CONTENIDO_INFORMATIVO_bo
go

drop procedure src_sps_negocio_taller_bo
go

drop procedure SRC_SPS_LISTADO_INDICADOR_HGSI
go

drop procedure SRC_SPS_OBTENER_KM_ULTIMAOT
go

drop procedure sgsnet_spi_proveedor
go